### ISSUE TITLE
Borer Shitlist (meta)

### ISSUE THREAD

**Issue by N3X15** [vgstation-coders/vgstation13#1902]
- [x] Poll on whether borers should stay at all (Result: Yes)
- [x] Set universal_understand to 1
- [x] Redo vent crawling (uses handle_ventcrawl() now)
- [x] Objectives are fucked
- [x] Borer chat not relayed to admins
- [x] Borer chat still has the ; at the front
